# Generated by Django 5.1.1 on 2024-09-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akasabackapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='categoryname',
        ),
    ]
