# Generated by Django 5.1.1 on 2024-09-22 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akasabackapp', '0003_product_createdat_product_image_product_pdesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
